from dace.optimization.transfer.spaces.data_layout_space import DataLayoutSpace
from dace.optimization.transfer.spaces.map_permutation_space import MapPermutationSpace
from dace.optimization.transfer.spaces.map_tiling_space import MapTilingSpace